spring:
  profiles:
    active: dev
  main:
    banner-mode: "off"
  jpa:
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
  flyway:
    sql-migration-prefix: v
mybatis:
  mapper-locations: "classpath:/mapper/*Mapper.xml"
  configuration:
    use-actual-param-name: true
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true